name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  schedule:
    # Run nightly to check that tests are working with latest dependencies
    - cron: "0 0 * * *"

permissions:
  contents: read
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout commit locally
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            uv sync --all-extras --upgrade
          else
            uv sync --all-extras --frozen
          fi

      - name: List all installed packages
        run: uv pip freeze

      - name: Ruff check
        if: ${{ always() }}
        run: uv run ruff check

      - name: Ruff format
        if: ${{ always() }}
        run: uv run ruff format --check

      - name: Check typing with mypy
        if: ${{ always() }}
        run: uv run mypy src tests

      - name: Run tests
        if: ${{ always() }}
        env:
          TERMINAL_WIDTH: 3000
          _TYPER_FORCE_DISABLE_TERMINAL: 1
        run: uv run pytest -n auto tests --cov=src/ --cov-report term-missing
